# Generated by Django 3.2.13 on 2023-07-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplacementapplication',
            name='offer_accepted',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='placementapplication',
            name='offer_accepted',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
