# Generated by Django 3.2.13 on 2023-07-24 13:24

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0003_historicalinternship_internship'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinternship',
            name='designation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalinternship',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalinternship',
            name='rs_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='internship',
            name='designation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='internship',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='internship',
            name='rs_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalinternship',
            name='season',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[['summer', 'Summer'], ['winter', 'Winter'], ['autumn', 'Autumn'], ['spring', 'Spring']], max_length=10), default=list, size=4),
        ),
        migrations.AlterField(
            model_name='internship',
            name='season',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[['summer', 'Summer'], ['winter', 'Winter'], ['autumn', 'Autumn'], ['spring', 'Spring']], max_length=10), default=list, size=4),
        ),
        migrations.AlterField(
            model_name='placement',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='APIs.user'),
        ),
    ]
