# Generated by Django 3.2.13 on 2023-07-24 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0004_auto_20230724_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='APIs.user'),
        ),
    ]
