# Generated by Django 3.2.13 on 2023-07-24 17:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0005_alter_internship_changed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinternship',
            name='allowed_branch',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[['CSE', 'CSE'], ['EE', 'EE'], ['ME', 'ME'], ['MMAE', 'MMAE'], ['EP', 'EP']], max_length=10), default=list, size=4),
        ),
        migrations.AddField(
            model_name='internship',
            name='allowed_branch',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[['CSE', 'CSE'], ['EE', 'EE'], ['ME', 'ME'], ['MMAE', 'MMAE'], ['EP', 'EP']], max_length=10), default=list, size=4),
        ),
    ]
