# Generated by Django 3.2.13 on 2023-07-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0006_auto_20230724_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinternship',
            name='city_type',
            field=models.CharField(blank=True, choices=[['Domestic', 'Domestic'], ['International', 'International']], max_length=15),
        ),
        migrations.AddField(
            model_name='internship',
            name='city_type',
            field=models.CharField(blank=True, choices=[['Domestic', 'Domestic'], ['International', 'International']], max_length=15),
        ),
    ]
