# Generated by Django 3.2.13 on 2023-07-24 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0007_auto_20230724_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinternship',
            name='type_of_organisation',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='type_of_organisation',
        ),
    ]
