# Generated by Django 3.2.13 on 2023-07-24 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0008_auto_20230725_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinternship',
            name='contact_person_designation',
        ),
        migrations.RemoveField(
            model_name='historicalinternship',
            name='telephone_number',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='contact_person_designation',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='telephone_number',
        ),
    ]
