# Generated by Django 3.2.13 on 2023-11-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0013_auto_20231201_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalplacement',
            name='allowed_branch',
        ),
        migrations.RemoveField(
            model_name='historicalplacement',
            name='rs_eligible',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='allowed_branch',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='rs_eligible',
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='can_apply_placements',
            field=models.BooleanField(default=True, verbose_name='Placement_Registered'),
        ),
        migrations.AlterField(
            model_name='student',
            name='can_apply_placements',
            field=models.BooleanField(default=True, verbose_name='Placement_Registered'),
        ),
    ]
