# Generated by Django 3.2.13 on 2023-10-26 05:21

import django.contrib.postgres.fields
from django.db import migrations, models
from django.db.migrations.operations.special import RunPython


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0014_auto_20231026_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplacement',
            name='allowed_degree',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[['bTech', 'B.Tech'], ['ms/phd', 'MS/ PhD'], ['mTech', 'M.Tech']], max_length=10), default=list, size=3),
        ),
        migrations.AlterField(
            model_name='placement',
            name='allowed_degree',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[['bTech', 'B.Tech'], ['ms/phd', 'MS/ PhD'], ['mTech', 'M.Tech']], max_length=10), default=list, size=3),
        ),

    ]
